#!/bin/bash
# by Dominik Stanisław Suchora <suchora.dominik7@gmail.com>
# License: GNU GPLv3

shopt -s extglob

declare url delay='0.5' maxprocs='3' first='1' random='1' last

IFS=$'\n'

ucurl() {
    curl -L -g -s --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36' -H 'Accept-Encoding: gzip, deflate' --compressed "$@"
}

get_posts() {
    tr -d '\r\n\t\a\f' | reliq '
        div .post-layout; {
            . div .js-vote-count data-value | "%(data-value)v\n",
            . div .user-info m@v>"edited"; span .relativetime | "%(title)v\n",
            . div .user-info m@"edited"; span .relativetime | "%(title)v\n",

            . div .user-info m@v>"edited"; div .user-details; {
                . * l@[1] c@[0] | "%i\n" / line [1],
                . span .reputation-score | "%i\n" / tr ",",
                . span title=w>gold; span .badgecount | "%i\n",
                . span title=w>silver; span .badgecount | "%i\n",
                . span title=w>bronze; span .badgecount | "%i\n"
            } / tr "\n" "\a" echo "" "\n",

            . div .user-info m@"edited"; div .user-details; {
                . * l@[1] c@[0] | "%i\n" / line [1],
                . span .reputation-score | "%i\n" / tr ",",
                . span title=w>gold; span .badgecount | "%i\n",
                . span title=w>silver; span .badgecount | "%i\n",
                . span title=w>bronze; span .badgecount | "%i\n"
            } / tr "\n" "\a" echo "" "\n",

            . div class="s-prose js-post-body" | "%i\n",

            . li #E>comment-[0-9]+; {
                . div .comment-score; * c@[0] | "%i\n",
                . span .comment-copy | "%i\n",
                . span .comment-date; span title | "%(title)v\n" / sed "s/, L.*//",
                . div; a | "%i\n" / line [1],
                . a title | "%(title)v\n" / tr "0-9\n" "" "c"
            } | tr "\n" "\f" echo "" "\a" / echo "" "\n"
        } | tr "\n" "\t" echo "" "\n"
    '
}

get_page() {
    local -r t="$(ucurl "$1")"
    local _tmp1
    echo "$1" #link
    reliq '
        . h1 itemprop="name"; a | "%i\n",
        . div class="flex--item ws-nowrap mb8" | "%(title)v\n" / tr "0-9\n" "" "c",
        . div class="js-bookmark-count mt4" | "%(data-value)v\n",
        . div .ps-relative; a .post-tag | "%i\t" / echo "" "\n"
    ' <<< "$t"
    get_posts <<< "$t"
    for n in $(reliq 'div .pager-answers [0]; a rel="" href | "'"$url"'%(href)v\n"' <<< "$t")
    do
        echo "$n" >&2
        ucurl "$n" | get_posts
    done
}

get_json() {
    local -r rh="${1#*/questions/}"
    local -r name="${rh%%/*}"
    [ -e "$name" ] && return
    get_page "$1" | jq -RnMcs '
        (inputs | split("\n")) as $lines | 

        .["link"]=$lines[0] |
        .["title"]=$lines[1] |
        .["views"]=$lines[2] |
        .["bookmarks"]=$lines[3] |
        .["tags"]=($lines[4] | split("\t"))[:-1] |
        .["posts"]=($lines[5:-1] | map(split("\t") | {
            ("rating"):.[0],
            ("date"):.[1],
            ("edited"):.[2],
            ("author"):(.[3] | split("")[:-1] | {
                ("name"):.[0],
                ("reputation"):.[1],
                ("gbadge"):.[2],
                ("sbadge"):.[3],
                ("bbadge"):.[4]
            }),
            ("editor"):(.[4] | split("")[:-1] | {
                ("name"):.[0],
                ("reputation"):.[1],
                ("gbadge"):.[2],
                ("sbadge"):.[3],
                ("bbadge"):.[4]
            }),
            ("content"):.[5],
            ("comments"):(.[6] | split("")[:-1] | map(split("\f") | {
                ("score"):.[0],
                ("content"):.[1],
                ("date"):.[2],
                ("author"):.[3],
                ("reputation"):.[4]
            }))
        }))' > "$name"
    sleep "$delay" "$((RANDOM%random))"
}

get_question_list() {
    local g t l
    g="$first"
    t="$(ucurl "$1?tab=newest&pagesize=50&page=$g")"
    l="$(reliq 'a class="s-pagination--item js-pagination-item" m@B>"^[0-9][0-9]*$" | "%i\n"' <<< "$t" | tail -n1)"
    [ -z "$last" ] && last="$l"
    [ "$last" -gt "$l" ] && last="$l"
    echo "$last"
    while :
    do
        #[ -z "$(reliq 'a class="s-pagination--item js-pagination-item" rel="next"' <<< "$t")" ] && break
        for i in $(reliq 'a .s-link | "'"$url"'%(href)v\n"' <<< "$t")
        do
            [ "$(jobs | wc -l)" -gt "$maxprocs" ] && wait %%
            echo "$i"
            get_json "$i" &
        done
        wait
        
        #echo "$links" | parallel -j "$maxprocs" 'get_json {}'
    
        ((g++))
        [ "$g" -gt "$last" ] && break
        sleep "$delay" "$((RANDOM%random))"
        echo "$1?tab=newest&pagesize=50&page=$g"
        t="$(ucurl "$1?tab=newest&pagesize=50&page=$g")"
    done
}

get_tags() {
    local g t l
    g="$first"
    t="$(ucurl "$1?tab=populart&pagesize=50&page=$g")"
    l="$(reliq 'a class="s-pagination--item js-pagination-item" m@B>"^[0-9][0-9]*$" | "%i\n"' <<< "$t" | tail -n1)"
    [ -z "$last" ] && last="$l"
    [ "$last" -gt "$l" ] && last="$l"
    echo "$last"
    while :
    do
        for c in $(reliq 'a .post-tag href | "'"$url"'%(href)v\n"' <<< "$t")
        do
            echo "$c"
            #get_question_list "$c"
        done
        ((g++))
        [ "$g" -gt "$last" ] && break
        sleep "$delay" "$((RANDOM%random))"
        echo "$1?tab=newest&pagesize=50&page=$g"
        t="$(ucurl "$1?tab=popular&pagesize=50&page=$g")"
    done
}

usage() {
    printf '%s [OPTION]... [DIR] [URL]...\n\n' "${0##*/}"
    printf 'Options:\n  -d,\t--delay DELAY\tset delay in sleep format, by default 0.5 seconds\n'
    printf '  -r,\t--random NUM\tset number of randomness which will be added to delay, must be integer\n'
    printf '  -p,\t--max-procs NUM\tset number of processes to run at a time, by default set to 3\n'
    printf '  -f,\t--first NUM\tset first page\n'
    printf '  -l,\t--last NUM\tset last page\n'
    printf '  -h,\t--help\t\tshow this message\n\n'
    printf 'Note that options ought to be specified before the directory.\n'
}

#export -f ucurl get_json
#export PARALLEL_SHELL="$(type -p 'bash')"

while [ "$#" -gt 0 ]
do
    case "$1" in
        -d|--delay) delay="$2"; shift;;
        -r|--random) random="$2"; random="$((random+1))"; shift;;
        -p|--max-procs) maxprocs="$2"; shift;;
        -f|--first) first="$2"; shift;;
        -l|--last) last="$2"; shift;;
        -h|--help) usage >&2; exit;;
        -*) usage >&2; exit 1;;
        *) break;;
    esac
    shift
done

[ -n "$last" ] && [ "$first" -gt "$last" ] && exit 0;

[ "$#" -eq 0 ] && { usage >&2; exit 1; }
cd "$1" || { usage >&2; exit 1; }
shift

while [ "$#" -gt 0 ]
do
    url="$(sed -E 's/(http[s]:\/\/([[:alnum:]]+\.)+[[:alpha:]]+).*/\1/' <<< "$1")"
    case "$1" in
        http(s)://+(+([[:alnum:]]).)+([[:alpha:]])/questions/tagged/+([[:alnum:]-])?(\?*))
            get_question_list "${1%%\?*}";;
        http(s)://+(+([[:alnum:]]).)+([[:alpha:]])?([/]?(questions?(\?*))))
            get_question_list "$url/questions";;
        http?(s)://+(+([[:alnum:]]).)+([[:alpha:]])/questions/+([[:digit:]])?([/]?(*)))
            get_json "$1";;
        http?(s)://+(+([[:alnum:]]).)+([[:alpha:]])?([/]?(tags?(\?*))))
            get_tags "$url/tags";;
    esac
    shift
done
